#[derive(Debug)]
pub enum UsbHidReportError {
    PopBeforePush,
    UnexpectedEndCollection,
    ReportOutsideCollection,
    ReportIdMissing,
    ReportSizeMissing,
    ReportCountMissing,
    UsagePageMissing,
    UsageMissing,
    InvalidUsageRange,
    InvalidDesignatorIndexRange,
    InvalidStringIndexRange,
    InvalidReportId,
    InvalidBufferSize,
    InvalidLogicalValueRange,
    InvalidPhysicalValueRange,
    LogicalValueOutOfRange,
}
